name: CI/CD to GKE

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: venu-k
  REGION: us-central1
  REPOSITORY: backend-repo
  IMAGE: backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Authenticate Docker to Artifact Registry
        run: |
          cat <<EOF > /tmp/key.json
          ${{ secrets.GCP_SA_KEY }}
          EOF
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Build & Push Docker image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest .
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials venu-k-gke-cluster --zone us-central1-a --project ${PROJECT_ID}

      - name: Install GKE auth plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Deploy to GKE
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/backend-deployment --timeout=120s

